- name: Check that docker exists
  stat:
    path: ~/.nix-profile/bin/docker
  register: docker_exists

- name: install docker
  ansible.builtin.shell: nix-env -iA nixpkgs.docker
  when: not docker_exists.stat.exists

- name: create docker group if not exists
  ansible.builtin.group:
    name: docker
  become: yes

- name: add user to docker group
  ansible.builtin.shell: sudo usermod -aG docker $USER

- name: Check that docker-compose exists
  stat:
    path: ~/.nix-profile/bin/docker-compose
  register: docker_compose_exists

- name: install docker-compose
  ansible.builtin.shell: nix-env -iA nixpkgs.docker-compose
  when: not docker_compose_exists.stat.exists
