- name: Install build-essential package
  ansible.builtin.apt:
    name: build-essential
  become: yes
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Check that nvm exists
  stat:
    path: ~/.nvm
  register: nvm_exists

- name: Install nvm
  ansible.builtin.shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash
  when: not nvm_exists.stat.exists

- name: Install node 
  ansible.builtin.shell: source ~/.zshrc && nvm install --lts
  args:
    executable: /bin/bash

- name: Check that vim exists
  stat:
    path: ~/.nix-profile/bin/vim
  register: vim_exists

- name: Install vim
  ansible.builtin.shell: "nix-env -iA nixpkgs.vim"
  when: not vim_exists.stat.exists

- name: Check that tmux exists
  stat:
    path: ~/.nix-profile/bin/tmux
  register: tmux_exists

- name: Install tmux
  ansible.builtin.shell: "nix-env -iA nixpkgs.tmux"
  when: not tmux_exists.stat.exists

- name: Check that neofetch exists
  stat:
    path: ~/.nix-profile/bin/neofetch
  register: neofetch_exists

- name: Install neofetch
  ansible.builtin.shell: "nix-env -iA nixpkgs.neofetch"
  when: not neofetch_exists.stat.exists

- name: Check that htop exists
  stat:
    path: ~/.nix-profile/bin/htop
  register: htop_exists

- name: Install htop
  ansible.builtin.shell: "nix-env -iA nixpkgs.htop"
  when: not htop_exists.stat.exists

- name: Check that speedtest exists
  stat:
    path: ~/.nix-profile/bin/speedtest
  register: speedtest_exists

- name: Install speedtest
  ansible.builtin.shell: "nix-env -iA nixpkgs.speedtest-cli"
  when: not speedtest_exists.stat.exists